site_name: English SDK for Apache Spark
theme:
  name: material
  logo: _static/english-sdk-spark-reverse.svg
  features:
    - content.code.copy

repo_url: https://github.com/pyspark-ai/pyspark-ai/

# Page tree
nav:
  - index.md
  - installation_and_setup.md
  - dataframe_transformation.md
  - data_ingestion.md
  - plot.md
  - dataframe_explanation.md
  - dataframe_verification.md
  - udf_generation.md
  - contributing.md
  - resources.md
  - Examples:
      - "notebooks/example.ipynb"
      - "notebooks/transform_dataframe.ipynb"
      - "notebooks/create_udf.ipynb"
      - "notebooks/vector_similarity_search.ipynb"
  - API Reference: reference/SUMMARY.md

plugins:
  - mkdocs-jupyter
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_options:
              show_if_no_docstring: true
            show_source: true

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
