name: publish website 

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'examples/**'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install poetry
        run: |
          pipx install "poetry>=1.3.0,<1.4.0"
      # Because generating of API docs requires actual import of all the files
      # we need to install all the dependencies that are used in the project.
      - run: poetry install --with website --extras all
      - run: poetry run mkdocs gh-deploy --force

